spring.application.name=ConferceRoom
spring.datasource.url=jdbc:mysql://localhost:3306/roomdata
spring.datasource.username=root
spring.datasource.password= Dipak@0014
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true